/**
 * Generates `worker/db/seed.sql` from the JSON fixtures in `worker/db/data`.
 * Run with Bun (`bun run worker/db/seed.ts`); the SQL is then applied with
 * `wrangler d1 execute project-management --local|--remote --file=worker/db/seed.sql`.
 *
 * The output clears every table (reverse-FK order) then re-inserts (FK order) with
 * explicit ids, so it is idempotent and references line up deterministically.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Row = Record<string, unknown>;

// Insert order = FK-safe order. `injectPk` tables have no id in their JSON and rely
// on array position, so we assign `pk = idx + 1` to match the cross-references.
const TABLES = [
  { file: "team.json", table: "teams", pk: "id", injectPk: true },
  { file: "project.json", table: "projects", pk: "id", injectPk: false },
  { file: "user.json", table: "users", pk: "userId", injectPk: true },
  { file: "projectTeam.json", table: "project_teams", pk: "id", injectPk: false },
  { file: "task.json", table: "tasks", pk: "id", injectPk: false },
  { file: "taskAssignment.json", table: "task_assignments", pk: "id", injectPk: false },
  { file: "attachment.json", table: "attachments", pk: "id", injectPk: false },
  { file: "comment.json", table: "comments", pk: "id", injectPk: false },
] as const;

const dataDir = join(import.meta.dirname, "data");

const quoteIdent = (name: string) => `"${name.replace(/"/g, '""')}"`;

const formatValue = (value: unknown): string => {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  return `'${String(value).replace(/'/g, "''")}'`;
};

const readRows = (file: string): Row[] =>
  JSON.parse(readFileSync(join(dataDir, file), "utf8")) as Row[];

function buildInsert(table: string, rows: Row[]): string {
  if (rows.length === 0) return "";
  // Column set = union of keys across all rows (stable order: first-seen).
  const columns: string[] = [];
  for (const row of rows) {
    for (const key of Object.keys(row)) {
      if (!columns.includes(key)) columns.push(key);
    }
  }
  const cols = columns.map(quoteIdent).join(", ");
  const values = rows
    .map(
      (row) =>
        `  (${columns.map((c) => formatValue(row[c])).join(", ")})`
    )
    .join(",\n");
  return `INSERT INTO ${quoteIdent(table)} (${cols}) VALUES\n${values};`;
}

const sections: string[] = [
  "-- Generated by worker/db/seed.ts — do not edit by hand.",
  "PRAGMA defer_foreign_keys = TRUE;",
  "",
  "-- Clear existing rows (reverse FK order)",
  ...[...TABLES].reverse().map(({ table }) => `DELETE FROM ${quoteIdent(table)};`),
  "",
  "-- Insert fixtures (FK order)",
];

for (const { file, table, pk, injectPk } of TABLES) {
  const rows = readRows(file);
  if (injectPk) rows.forEach((row, idx) => (row[pk] = idx + 1));
  sections.push(buildInsert(table, rows));
}

const outFile = join(import.meta.dirname, "seed.sql");
writeFileSync(outFile, sections.join("\n") + "\n");
console.log(`Wrote ${outFile}`);
